apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-hello-world
  template:
    metadata:
      labels:
        app: nodejs-hello-world
    spec:
      containers:
      - name: shubhamswami123/nodejs
        image: shubhamswami123/nodejs:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-hello-world-service
spec:
 type: NodePort
 selector:
    app: nodejs-hello-world
  ports:
    -port: 80
     targetPort: 3000
      NodePort: 30001
